[package]
name = "oltp_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = "0.19.0"
tracing = "0.1.38"
tracing-opentelemetry = "0.18"
tracing-subscriber = "0.3.17"
